id: AA1605C0F
title: Restorative Offering to the Eight Classes
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:02:42.071543
  last_modified_at: 2022-03-01 01:02:42.071549
